<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\..\SupportToolsServerCore\SupportToolsServerCore.Application.Abstractions\SupportToolsServerCore.Application.Abstractions.csproj" />
        <ProjectReference Include="..\..\SupportToolsServerCore\SupportToolsServerCore.Domain\SupportToolsServerCore.Domain.csproj" />
        <ProjectReference Include="..\..\SupportToolsServerShared\SupportToolsServerApiContracts\SupportToolsServerApiContracts.csproj" />
        <ProjectReference Include="..\..\SystemTools\SystemTools.Application.Abstractions\SystemTools.Application.Abstractions.csproj" />
        <ProjectReference Include="..\..\SystemTools\SystemTools.Domain.Abstractions\SystemTools.Domain.Abstractions.csproj" />
    </ItemGroup>

</Project>
